-- Schema for Supabase (PostgreSQL)
-- Generated from init_db and init_log_db in stock_dashboard.py

-- 1. Table: scan_results
-- Stores individual stock scan results and technical scores
CREATE TABLE IF NOT EXISTS scan_results (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticker TEXT,
    scan_date TEXT,
    scan_time TEXT,
    price DOUBLE PRECISION,
    bull_score DOUBLE PRECISION,
    bear_score DOUBLE PRECISION,
    score_diff DOUBLE PRECISION,
    signal_type TEXT,
    market_regime TEXT,
    relative_vol DOUBLE PRECISION,
    rsi DOUBLE PRECISION,
    mtf_status TEXT,
    mtf_score DOUBLE PRECISION,
    conviction_score DOUBLE PRECISION,
    outcome_label TEXT,
    outcome_pct DOUBLE PRECISION,
    verified_date TEXT
);

-- 2. Table: trading_log
-- Stores performance tracking and session data
CREATE TABLE IF NOT EXISTS trading_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_id TEXT,
    timestamp TEXT,
    session_flag TEXT,
    ticker TEXT,
    signal TEXT,
    last_price DOUBLE PRECISION,
    high_price DOUBLE PRECISION,
    market_context TEXT,
    outcome_t3_pct DOUBLE PRECISION,
    max_dd_pct DOUBLE PRECISION,
    status TEXT,
    verified_date TEXT
);

-- Note: In Supabase, you might want to enable RLS (Row Level Security) 
-- after creating these tables if they will be accessed by a client-side app.
